image: gradle:8-jdk21-alpine

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dhttp.proxyHost=194.254.199.96 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=194.254.199.96 -Dhttps.proxyPort=3128"

before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"
  - gradle --version

#JOB 1 - build 
build:
  stage: build
  script: gradle --build-cache assemble
  artifacts:
    name: "mon-app-cpoo"
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

#JOB 2 - test 
test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

#JOB 3 - deploy
pages:
  stage: deploy
  script:
    - gradle javadoc
    - mkdir -p public
    - cp -r build/docs/javadoc/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"