image: gradle:jdk17

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dhttp.proxyHost=proxy.univ-paris-diderot.fr -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.univ-paris-diderot.fr -Dhttps.proxyPort=3128"

before_script:
  - gradle --version

build:
  stage: build
  script:
    - gradle assemble --info
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  dependencies:
    - build